databases:
  - name: stocks
    databaseName: stocks
    user: stocks

services:
  - type: web
    name: stocks
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocks
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
